export const IC_CONTACT = require("./icons/ic_contact.png")
export const IC_MENU = require('./icons/ic_menu.png')
export const IC_CAMERA = require('./icons/ic_camera.png')
export const IC_SEARCH = require('./icons/ic_searchicon.png')
export const IC_HISTORY = require('./icons/ic_history.png')
export const IC_LINE = require('./icons/ic_line.png')
export const IC_SMALL_CALL = require('./icons/ic_minicall.png')
export const IC_INFO_ICON = require('./icons/ic_info.png')
export const IC_PROFILE = require('./icons/ic_profile.png')
export const IC_UPDATE_AVATAR = require('./icons/ic_yellowcamera.png')
export const IC_DOWN_ARROW = require('./icons/ic_arrowdown.png')
export const IC_ADD_GREEN_BUTTON = require('./icons/ic_add.png')
export const IC_BACKGROUND_CIRCLE = require('./icons/ic_graycircle.png')
export const IC_ARROW_BACK_BUTTON = require('./icons/ic_arrowback.png')
export const IC_CALL_BUTTON = require('./icons/ic_callbutton.png')
export const IC_MESSAGE_BUTTON = require('./icons/ic_chatbtn.png')
export const IC_FACETIME = require('./icons/ic_facetimebtn.png')
export const IC_EMAIL = require('./icons/ic_email.png')
export const IC_LINE_DOWN = require('./icons/ic_linedown.png')
export const IC_ADD_PLUS = require('./icons/ic_addplusyellow.png')
export const IC_REMOVE = require('./icons/ic_removeline.png')


export const IMG_LOGIN_BACKGROUND = require('./images/login_background.png')
export const IMG_LOGO_APP = require('./images/logo_app.png')
export const IMG_LOGO_APP_SMALL = require('./images/login_small_icon.png')
export const IMG_PROFILE_AVATAR = require('./images/profile_contact.jpeg')
